version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: rjwedding-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - host

volumes:
  mongodb_data:
